/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoMathPlugin
});
module.exports = __toCommonJS(main_exports);

// src/plugin.ts
var import_obsidian3 = require("obsidian");

// src/rules.ts
var DEFAULT_RULES = [
  { trigger: "\\frac", expand: "\\frac{}{}" },
  { trigger: "\\dfrac", expand: "\\dfrac{}{}" },
  { trigger: "\\tfrac", expand: "\\tfrac{}{}" },
  { trigger: "\\cfrac", expand: "\\cfrac{}{}" },
  { trigger: "\\binom", expand: "\\binom{}{}" },
  { trigger: "\\dbinom", expand: "\\dbinom{}{}" },
  { trigger: "\\tbinom", expand: "\\tbinom{}{}" },
  { trigger: "\\text", expand: "\\text{}" },
  { trigger: "\\sqrt", expand: "\\sqrt{}" },
  { trigger: "\\root", expand: "\\sqrt[]{}" },
  { trigger: "\\sum", expand: "\\sum_{}^{}" },
  { trigger: "\\int", expand: "\\int_{}^{}" },
  { trigger: "\\lim_", expand: "\\lim_{}" },
  { trigger: "\\limsup", expand: "\\limsup_{}" },
  { trigger: "\\liminf", expand: "\\liminf_{}" },
  { trigger: "\\max", expand: "\\max_{}" },
  { trigger: "\\min", expand: "\\min_{}" },
  { trigger: "\\inf_", expand: "\\inf_{}" },
  { trigger: "\\sup", expand: "\\sup_{}" },
  { trigger: "\\log", expand: "\\log_{}" },
  { trigger: "\\pow", expand: "{}^{}" },
  { trigger: "\\abs", expand: "\\left|{}\\right|" },
  { trigger: "\\norm", expand: "\\left\\|{}\\right\\|" },
  { trigger: "\\vec", expand: "\\vec{}" },
  { trigger: "\\hat", expand: "\\hat{}" },
  { trigger: "\\bar", expand: "\\bar{}" },
  { trigger: "\\overline", expand: "\\overline{}" },
  { trigger: "\\underline", expand: "\\underline{}" },
  { trigger: "^^", expand: "^{}" },
  { trigger: "__", expand: "_{}" },
  { trigger: "\\align", expand: "\\begin{align}\n|\n\\end{align}" },
  { trigger: "\\aligned", expand: "\\begin{aligned}\n|\n\\end{aligned}" },
  { trigger: "\\gather", expand: "\\begin{gather}\n|\n\\end{gather}" },
  { trigger: "\\cases", expand: "\\begin{cases}\n|\n\\end{cases}" },
  { trigger: "\\array", expand: "\\begin{array}{}\n|\n\\end{array}" },
  { trigger: "\\matrix", expand: "\\begin{matrix}\n|\n\\end{matrix}" },
  { trigger: "\\pmatrix", expand: "\\begin{pmatrix}\n|\n\\end{pmatrix}" },
  { trigger: "\\bmatrix", expand: "\\begin{bmatrix}\n|\n\\end{bmatrix}" },
  { trigger: "\\split", expand: "\\begin{split}\n|\n\\end{split}" }
];

// src/constants.ts
var SMART_LIMIT_OPERATORS = {
  "\\int": {
    inline: "\\int_{}^{}",
    display: "\\int\\limits_{}^{}"
  }
  // Note: \sum works correctly without explicit \limits in both modes
  // Uncomment if needed:
  // "\\sum": {
  //     inline: "\\sum_{}^{}",
  //     display: "\\sum\\limits_{}^{}",
  // },
};
var DEFAULT_SETTINGS = {
  enabled: true,
  rulesPath: "rules.json",
  debug: false,
  smartLimits: false,
  // disabled by default - enable in settings if needed
  maxScanLines: 50,
  // maximum lines to scan for multiline $$...$$ blocks
  rulesJson: JSON.stringify(DEFAULT_RULES, null, 2)
};

// src/utils.ts
function normalizeText(s) {
  return (s != null ? s : "").replace(/[\u200B\uFEFF]/g, "");
}

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/modals.ts
var import_obsidian = require("obsidian");
var ConflictResolutionModal = class extends import_obsidian.Modal {
  constructor(app, groups) {
    super(app);
    this.selections = /* @__PURE__ */ new Map();
    this.resolver = null;
    this.completed = false;
    this.groups = groups;
    for (const group of groups) {
      this.selections.set(group.key, group.defaultIndex);
    }
  }
  openAndWait() {
    const promise = new Promise((resolve) => {
      this.resolver = resolve;
    });
    this.open();
    return promise;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Resolve conflicts" });
    contentEl.createEl("p", {
      text: "Choose the expansion to keep for each trigger."
    });
    for (const group of this.groups) {
      new import_obsidian.Setting(contentEl).setName(`Trigger: ${group.trigger}`).setDesc("Select the expansion to keep").addDropdown((d) => {
        group.options.forEach((opt, idx) => {
          d.addOption(String(idx), opt.expand);
        });
        d.setValue(String(group.defaultIndex));
        d.onChange((v) => {
          this.selections.set(group.key, Number(v));
        });
      });
    }
    const actions = contentEl.createDiv();
    new import_obsidian.Setting(actions).addButton(
      (b) => b.setButtonText("Save").setCta().onClick(() => {
        var _a, _b;
        const resolved = /* @__PURE__ */ new Map();
        for (const group of this.groups) {
          const idx = (_a = this.selections.get(group.key)) != null ? _a : group.defaultIndex;
          resolved.set(group.key, group.options[idx]);
        }
        this.completed = true;
        this.close();
        (_b = this.resolver) == null ? void 0 : _b.call(this, resolved);
      })
    ).addButton(
      (b) => b.setButtonText("Cancel").onClick(() => {
        var _a;
        this.completed = true;
        this.close();
        (_a = this.resolver) == null ? void 0 : _a.call(this, null);
      })
    );
  }
  onClose() {
    var _a;
    if (!this.completed) {
      (_a = this.resolver) == null ? void 0 : _a.call(this, null);
    }
    this.resolver = null;
  }
};
function resolveRuleConflicts(app, groups) {
  const modal = new ConflictResolutionModal(app, groups);
  return modal.openAndWait();
}

// src/settings.ts
var AutoMathSettingsTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Enabled").setDesc("Turn the plugin on or off.").addToggle(
      (t) => t.setValue(this.plugin.settings.enabled).onChange(async (v) => {
        this.plugin.settings.enabled = v;
        await this.plugin.saveSettings();
        this.plugin._renderStatus();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Rules file path").setDesc(
      `Path relative to plugin folder (default: rules.json). Full path: ${this.plugin.getFullRulesPath()}`
    ).addText(
      (t) => t.setValue(this.plugin.settings.rulesPath).onChange(async (v) => {
        this.plugin.settings.rulesPath = v.trim() || "rules.json";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Reload rules now").setDesc("Force reload from the external file and validate JSON").addButton(
      (b) => b.setButtonText("Reload").onClick(async () => {
        const ok = await this.plugin._loadExternalRules(true);
        new import_obsidian2.Notice(
          ok ? `Rules reloaded (${this.plugin._getRules().length})` : "Failed to reload rules (see console)"
        );
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Create / open rules file").setDesc("Create external rules file if missing and open it in a new tab").addButton(
      (b) => b.setButtonText("Create / open").onClick(async () => {
        await this.plugin._ensureRulesFile();
        await this.plugin._openRulesFile();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Debug logs").setDesc("Log rule matches and loading to the developer console").addToggle(
      (t) => t.setValue(this.plugin.settings.debug).onChange(async (v) => {
        this.plugin.settings.debug = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Smart limits").setDesc(
      "Automatically choose \\int/\\int\\limits when expanding inside $...$ or $$...$$."
    ).addToggle(
      (t) => t.setValue(this.plugin.settings.smartLimits).onChange(async (v) => {
        this.plugin.settings.smartLimits = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Custom rules editor").setHeading();
    const help = containerEl.createDiv();
    help.setText(
      "Edit your rules below. Use double backslashes \\\\ in triggers/expansions. '|' marks cursor; '{}' places cursor inside the first braces."
    );
    help.setAttr("style", "margin: 6px 0; opacity: .8;");
    let work = this.plugin._workRules || null;
    let filter = "";
    let isDirty = false;
    const metaEl = containerEl.createDiv();
    metaEl.setAttr("style", "margin: 6px 0;");
    const statusEl = metaEl.createDiv();
    const warningsEl = metaEl.createDiv();
    const controlsEl = containerEl.createDiv();
    new import_obsidian2.Setting(controlsEl).setName("Filter").setDesc("Filter by trigger or expansion text").addText((t) => {
      t.setPlaceholder("\\\\frac, \\\\int, begin{align}").onChange((v) => {
        filter = v.trim().toLowerCase();
        void renderEditor();
      });
    });
    new import_obsidian2.Setting(controlsEl).setName("Sort").setDesc("Sort rules by trigger (a to z)").addButton(
      (b) => b.setButtonText("Sort now").onClick(() => {
        if (work) {
          work.sort((a, b2) => a.trigger.localeCompare(b2.trigger));
          markDirty();
          void renderEditor();
        }
      })
    );
    const editorEl = containerEl.createDiv();
    const getIssues = () => {
      var _a;
      const emptyTriggers = (work || []).filter((r) => !r.trigger.trim()).length;
      const emptyExpands = (work || []).filter((r) => !r.expand.trim()).length;
      const counts = /* @__PURE__ */ new Map();
      for (const rule of work || []) {
        const key = normalizeText(rule.trigger).trim();
        if (!key)
          continue;
        counts.set(key, ((_a = counts.get(key)) != null ? _a : 0) + 1);
      }
      const conflicts = [...counts.entries()].filter(([, count]) => count > 1).map(([key]) => key);
      return { emptyTriggers, emptyExpands, conflicts };
    };
    const updateMeta = () => {
      statusEl.setText(isDirty ? "Unsaved changes" : "All changes saved");
      const issues = getIssues();
      const parts = [];
      if (issues.emptyTriggers)
        parts.push(`Empty triggers: ${issues.emptyTriggers}`);
      if (issues.emptyExpands)
        parts.push(`Empty expansions: ${issues.emptyExpands}`);
      if (issues.conflicts.length)
        parts.push(`Conflicting triggers: ${issues.conflicts.join(", ")}`);
      warningsEl.setText(parts.length ? parts.join(" \u2022 ") : "");
      warningsEl.setAttr("style", parts.length ? "opacity: .85;" : "opacity: .5;");
    };
    const markDirty = () => {
      isDirty = true;
      updateMeta();
    };
    const renderEditor = async (opts = { reload: false }) => {
      editorEl.empty();
      if (!work || opts.reload) {
        await this.plugin._loadExternalRules(true);
        work = this.plugin._getRules().map((r) => ({ ...r }));
        this.plugin._workRules = work;
        isDirty = false;
      }
      const list = editorEl.createDiv();
      list.addClass("am-rules-list");
      if (work) {
        work.forEach((rule, idx) => {
          const searchable = `${rule.trigger} ${rule.expand}`.toLowerCase();
          if (filter && !searchable.includes(filter))
            return;
          const row = list.createDiv({ cls: "am-rule-row" });
          new import_obsidian2.Setting(row).setName("Trigger").addText((t) => {
            t.setValue(rule.trigger).onChange((v) => {
              rule.trigger = v;
              markDirty();
            });
          });
          new import_obsidian2.Setting(row).setName("Expand").addText((t) => {
            t.setValue(rule.expand).onChange((v) => {
              rule.expand = v;
              markDirty();
            });
          });
          new import_obsidian2.Setting(row).addButton(
            (b) => b.setButtonText("Delete").onClick(() => {
              if (work) {
                work.splice(idx, 1);
                markDirty();
                void renderEditor();
              }
            })
          );
          row.createEl("hr");
        });
      }
      const addWrap = editorEl.createDiv();
      new import_obsidian2.Setting(addWrap).setName("Add new rule").addButton(
        (b) => b.setButtonText("Add").onClick(() => {
          if (work) {
            work.push({ trigger: "\\\\new", expand: "\\\\new{}" });
            markDirty();
            void renderEditor();
          }
        })
      );
      const actions = editorEl.createDiv();
      new import_obsidian2.Setting(actions).setName("Save rules to file").setDesc(`Writes JSON to ${this.plugin.getFullRulesPath()}`).addButton(
        (b) => b.setButtonText("Save").onClick(async () => {
          var _a;
          if (!work)
            return;
          let removedEmpty = 0;
          const candidates = [];
          for (const r of work) {
            if (!r || typeof r.trigger !== "string" || typeof r.expand !== "string") {
              removedEmpty++;
              continue;
            }
            const trigger = r.trigger.trim();
            const expand = r.expand.trim();
            if (!trigger || !expand) {
              removedEmpty++;
              continue;
            }
            candidates.push({ trigger, expand });
          }
          const byKey = /* @__PURE__ */ new Map();
          for (const r of candidates) {
            const key = normalizeText(r.trigger).trim();
            const list2 = byKey.get(key);
            if (list2) {
              list2.push(r);
            } else {
              byKey.set(key, [r]);
            }
          }
          const resolved = [];
          const conflicts = [];
          for (const [key, list2] of byKey) {
            const options = [];
            const expandIndex = /* @__PURE__ */ new Map();
            let defaultIndex = 0;
            for (let i = 0; i < list2.length; i++) {
              const rule = list2[i];
              if (!expandIndex.has(rule.expand)) {
                expandIndex.set(rule.expand, options.length);
                options.push(rule);
              }
              if (i === list2.length - 1) {
                defaultIndex = (_a = expandIndex.get(rule.expand)) != null ? _a : 0;
              }
            }
            if (options.length <= 1) {
              resolved.push(list2[list2.length - 1]);
            } else {
              conflicts.push({
                key,
                trigger: list2[list2.length - 1].trigger,
                options,
                defaultIndex
              });
            }
          }
          if (conflicts.length) {
            const selection = await resolveRuleConflicts(this.app, conflicts);
            if (!selection) {
              new import_obsidian2.Notice("Save canceled");
              return;
            }
            for (const group of conflicts) {
              const chosen = selection.get(group.key);
              if (chosen)
                resolved.push(chosen);
            }
          }
          const cleaned = resolved.sort((a, b2) => a.trigger.localeCompare(b2.trigger));
          const text = JSON.stringify(cleaned, null, 2) + "\n";
          const ok = await this.plugin._writeVaultFile(
            this.plugin.getFullRulesPath(),
            text
          );
          if (ok) {
            this.plugin._workRules = null;
            isDirty = false;
            await this.plugin._loadExternalRules(true);
            const parts = [];
            if (conflicts.length) {
              parts.push(`resolved ${conflicts.length} conflicts`);
            }
            if (removedEmpty) {
              parts.push(`removed ${removedEmpty} empty`);
            }
            const removedDuplicates = candidates.length - cleaned.length;
            if (removedDuplicates > 0) {
              parts.push(`removed ${removedDuplicates} duplicates`);
            }
            new import_obsidian2.Notice(
              parts.length ? `Saved ${cleaned.length} rules (${parts.join(", ")})` : `Saved ${cleaned.length} rules`
            );
            await renderEditor({ reload: true });
          } else {
            new import_obsidian2.Notice("Failed to save rules (see console)");
          }
        })
      ).addButton(
        (b) => b.setButtonText("Discard").onClick(() => {
          this.plugin._workRules = null;
          work = null;
          isDirty = false;
          new import_obsidian2.Notice("Changes discarded");
          void renderEditor({ reload: true });
        })
      );
      updateMeta();
    };
    void renderEditor();
  }
};

// src/plugin.ts
var AutoMathPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.statusEl = null;
    this._rules = [];
    this._workRules = null;
  }
  async onload() {
    var _a, _b;
    await this.loadSettings();
    const version = (_b = (_a = this.manifest) == null ? void 0 : _a.version) != null ? _b : "unknown";
    console.debug("[Auto Math] loaded v" + version);
    const rulesPath = this.getFullRulesPath();
    const exists = await this._rulesFileExists(rulesPath);
    new import_obsidian3.Notice(
      exists ? `Auto Math: external rules found` : `Auto Math: external rules not found`
    );
    await this._loadExternalRules(true);
    new import_obsidian3.Notice(`Auto Math: ${this._getRules().length} active rules`);
    this.statusEl = this.addStatusBarItem();
    this._renderStatus();
    this.addRibbonIcon("divide", "Toggle plugin", () => {
      void this._toggle();
    });
    this.addCommand({
      id: "toggle",
      name: "Toggle",
      callback: () => {
        void this._toggle();
      }
    });
    this.addCommand({
      id: "reload-rules",
      name: "Reload rules",
      callback: async () => {
        const ok = await this._loadExternalRules(true);
        new import_obsidian3.Notice(
          ok ? `Rules reloaded (${this._getRules().length})` : "Failed to reload rules (see console)"
        );
      }
    });
    this.addCommand({
      id: "dump-rules",
      name: "Dump rules to console",
      callback: () => {
        console.debug("[Auto Math] active rules:", this._getRules());
        new import_obsidian3.Notice(`Dumped ${this._getRules().length} rules to console`);
      }
    });
    this.addCommand({
      id: "create-or-open",
      name: "Create or open rules file",
      callback: async () => {
        await this._ensureRulesFile();
        await this._openRulesFile();
      }
    });
    this._registerRulesWatcher();
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor) => {
        if (!this.settings.enabled)
          return;
        if (!editor)
          return;
        try {
          this._maybeExpand(editor);
        } catch (e) {
          console.error("[Auto Math] expand error", e);
        }
      })
    );
    this.addSettingTab(new AutoMathSettingsTab(this.app, this));
  }
  getFullRulesPath() {
    return `${this.manifest.dir}/${this.settings.rulesPath}`;
  }
  async _toggle() {
    this.settings.enabled = !this.settings.enabled;
    await this.saveSettings();
    this._renderStatus();
    new import_obsidian3.Notice(`Auto Math: ${this.settings.enabled ? "ON" : "OFF"}`);
  }
  _renderStatus() {
    if (!this.statusEl)
      return;
    this.statusEl.setText(this.settings.enabled ? "Auto Math: ON" : "Auto Math: OFF");
  }
  async _rulesFileExists(path) {
    try {
      return await this.app.vault.adapter.exists(path);
    } catch (e) {
      return false;
    }
  }
  async _readVaultFile(path) {
    try {
      return await this.app.vault.adapter.read(path);
    } catch (e) {
      if (e && typeof e === "object" && "code" in e && e.code === "ENOENT") {
        if (this.settings.debug) {
          console.debug("[Auto Math] rules file not found (using built-in rules):", path);
        }
      } else {
        console.error("[Auto Math] failed to read rules file:", path, e);
      }
      return null;
    }
  }
  async _writeVaultFile(path, text) {
    try {
      await this.app.vault.adapter.write(path, text);
      return true;
    } catch (e) {
      console.error("[Auto Math] write error", e);
      return false;
    }
  }
  async _ensureRulesFile() {
    const p = this.getFullRulesPath();
    if (!await this._rulesFileExists(p)) {
      const def = JSON.stringify(DEFAULT_RULES, null, 2) + "\n";
      const ok = await this._writeVaultFile(p, def);
      new import_obsidian3.Notice(
        ok ? `Created rules file at ${p}` : "Failed to create rules file (see console)"
      );
    }
  }
  async _openRulesFile() {
    const p = this.getFullRulesPath();
    try {
      const file = this.app.vault.getAbstractFileByPath(p);
      if (file && file instanceof import_obsidian3.TFile) {
        await this.app.workspace.getLeaf(true).openFile(file);
      }
    } catch (e) {
      console.error("[Auto Math] cannot open rules file", e);
    }
  }
  async _loadExternalRules(showErrors) {
    const p = this.getFullRulesPath();
    const raw = await this._readVaultFile(p);
    if (raw && raw.trim()) {
      const parsed = this._parseRulesText(raw, showErrors);
      if (parsed && parsed.length) {
        this._rules = parsed;
        if (this.settings.debug)
          console.debug("[Auto Math] loaded external rules", parsed);
        return true;
      }
      if (showErrors)
        console.error("[Auto Math] external rules present but invalid at", p);
    } else {
      if (showErrors && this.settings.debug) {
        console.debug("[Auto Math] external rules not found, using built-in pack");
      }
    }
    const fallback = this._parseRulesText(this.settings.rulesJson, showErrors);
    this._rules = Array.isArray(fallback) ? fallback : [];
    if (this.settings.debug)
      console.debug("[Auto Math] loaded fallback rules", this._rules);
    return !!this._rules.length;
  }
  _parseRulesText(text, showErrors) {
    try {
      const trimmed = text.trim();
      if (trimmed.startsWith("[")) {
        const arr2 = JSON.parse(trimmed);
        return this._sanitizeRules(arr2);
      }
      const lines = trimmed.split(/\n+/).map((l) => l.trim()).filter(Boolean);
      const arr = [];
      for (const l of lines) {
        try {
          arr.push(JSON.parse(l));
        } catch (e) {
        }
      }
      return this._sanitizeRules(arr);
    } catch (e) {
      if (showErrors)
        console.error("[Auto Math] cannot parse rules", e);
      return null;
    }
  }
  _sanitizeRules(arr) {
    if (!Array.isArray(arr))
      return [];
    return arr.filter(
      (r) => r !== null && typeof r === "object" && typeof r.trigger === "string" && typeof r.expand === "string"
    ).map((r) => ({
      trigger: normalizeText(r.trigger),
      expand: r.expand
    })).sort((a, b) => b.trigger.length - a.trigger.length);
  }
  _registerRulesWatcher() {
    const onChange = async (file) => {
      const currentPath = this.getFullRulesPath();
      if (file && file.path === currentPath) {
        if (this.settings.debug) {
          console.debug("[Auto Math] detected change in rules file:", currentPath);
        }
        await this._loadExternalRules(true);
        new import_obsidian3.Notice(`Auto Math: reloaded (${this._getRules().length})`);
      }
    };
    this.registerEvent(this.app.vault.on("modify", onChange));
    this.registerEvent(this.app.vault.on("create", onChange));
    this.registerEvent(this.app.vault.on("delete", onChange));
  }
  _getRules() {
    return this._rules || [];
  }
  /**
   * Detect whether the cursor is inside $...$ or $$...$$ blocks.
   *
   * Supports both single-line and multiline $$...$$ blocks.
   * For multiline blocks, scans up to maxScanLines in both directions.
   */
  _getMathContext(editor, pos) {
    var _a;
    const currentLine = pos.line;
    const lineText = (_a = editor.getLine(currentLine)) != null ? _a : "";
    const len = lineText.length;
    const display = [];
    for (let i = 0; i < len - 1; i++) {
      if (lineText[i] === "$" && lineText[i + 1] === "$") {
        display.push(i);
        i++;
      }
    }
    for (let i = 0; i + 1 < display.length; i += 2) {
      const start = display[i];
      const end = display[i + 1] + 2;
      if (pos.ch > start && pos.ch <= end) {
        return { type: "display" };
      }
    }
    const singles = [];
    for (let i = 0; i < len; i++) {
      if (lineText[i] === "$") {
        if (i + 1 < len && lineText[i + 1] === "$") {
          i++;
          continue;
        }
        singles.push(i);
      }
    }
    for (let i = 0; i + 1 < singles.length; i += 2) {
      const start = singles[i];
      const end = singles[i + 1] + 1;
      if (pos.ch > start && pos.ch <= end) {
        return { type: "inline" };
      }
    }
    const maxScan = this.settings.maxScanLines || 50;
    let displayStart = null;
    for (let i = currentLine - 1; i >= Math.max(0, currentLine - maxScan); i--) {
      const line = editor.getLine(i).trim();
      if (line === "$$") {
        displayStart = i;
        break;
      }
    }
    if (displayStart !== null) {
      for (let i = currentLine + 1; i < Math.min(editor.lineCount(), currentLine + maxScan); i++) {
        const line = editor.getLine(i).trim();
        if (line === "$$") {
          if (this.settings.debug) {
            console.debug(`[Auto Math] multiline display mode detected: lines ${displayStart}-${i}`);
          }
          return { type: "display" };
        }
      }
    }
    return { type: "none" };
  }
  _maybeExpand(editor) {
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    if (cursor.ch === 0)
      return;
    const lastChar = lineText[cursor.ch - 1];
    if (!/[a-zA-Z\\^_}]/.test(lastChar))
      return;
    const uptoRaw = lineText.slice(0, cursor.ch);
    const upto = normalizeText(uptoRaw);
    const rules = this._getRules();
    if (!rules.length)
      return;
    for (const rule of rules) {
      const trig = normalizeText(rule.trigger);
      if (trig.length > upto.length)
        continue;
      if (!upto.endsWith(trig))
        continue;
      const delta = uptoRaw.length - upto.length;
      const start = cursor.ch - trig.length - delta;
      const before = lineText.slice(0, start);
      const after = lineText.slice(cursor.ch);
      let expanded = rule.expand;
      if (this.settings.smartLimits) {
        const smart = SMART_LIMIT_OPERATORS[trig];
        if (smart) {
          const ctx = this._getMathContext(editor, cursor);
          if (ctx.type === "display") {
            expanded = smart.display;
          } else {
            expanded = smart.inline;
          }
        }
      }
      if (expanded.includes("\n")) {
        this._expandMultiline(editor, cursor, before, after, expanded);
      } else {
        this._expandSingleLine(editor, cursor, before, after, expanded);
      }
      if (this.settings.debug) {
        console.debug("[Auto Math] matched trigger", trig, "expanded to", expanded);
      }
      return;
    }
  }
  /**
   * Expand a single-line template
   */
  _expandSingleLine(editor, cursor, before, after, expanded) {
    editor.setLine(cursor.line, before + expanded + after);
    const idxBraces = expanded.indexOf("{}");
    if (idxBraces >= 0) {
      const pos = before.length + expanded.indexOf("{") + 1;
      editor.setCursor({ line: cursor.line, ch: pos });
    } else {
      const pipe = expanded.indexOf("|");
      if (pipe >= 0) {
        editor.setLine(cursor.line, before + expanded.replace("|", "") + after);
        const pos = before.length + pipe;
        editor.setCursor({ line: cursor.line, ch: pos });
      } else {
        editor.setCursor({
          line: cursor.line,
          ch: before.length + expanded.length
        });
      }
    }
  }
  /**
   * Expand a multiline template (containing \n)
   */
  _expandMultiline(editor, cursor, before, after, expanded) {
    const lines = expanded.split("\n");
    const cursorLine = cursor.line;
    let cursorLineOffset = 0;
    let cursorChOffset = 0;
    let foundCursor = false;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const pipeIdx = line.indexOf("|");
      if (pipeIdx >= 0 && !foundCursor) {
        cursorLineOffset = i;
        cursorChOffset = pipeIdx;
        foundCursor = true;
        lines[i] = line.replace("|", "");
      }
      if (!foundCursor) {
        const braceIdx = line.indexOf("{}");
        if (braceIdx >= 0) {
          cursorLineOffset = i;
          cursorChOffset = braceIdx + 1;
          foundCursor = true;
        }
      }
    }
    editor.setLine(cursorLine, before + lines[0] + (lines.length === 1 ? after : ""));
    if (lines.length > 1) {
      for (let i = 1; i < lines.length; i++) {
        const isLastLine = i === lines.length - 1;
        const content = isLastLine ? lines[i] + after : lines[i];
        editor.replaceRange(
          "\n" + content,
          { line: cursorLine + i - 1, ch: Infinity }
        );
      }
    }
    if (foundCursor) {
      const finalLine = cursorLine + cursorLineOffset;
      const finalCh = (cursorLineOffset === 0 ? before.length : 0) + cursorChOffset;
      editor.setCursor({ line: finalLine, ch: finalCh });
    } else {
      editor.setCursor({
        line: cursorLine + lines.length - 1,
        ch: Infinity
      });
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = {
      ...DEFAULT_SETTINGS,
      ...data != null ? data : {}
    };
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */